### ISSUE TITLE
Koans with IntelliJ IDEA

### ISSUE THREAD

**Issue by profesorasix** [JavaKoan/java-koans#2]
Hello Nick, 

Could you provide a quick guide setting up JavaKoans with IntelliJ IDEA?. I would like to see the results with the usual green or red bar in the IDE, like you do in your video.

I have imported the maven project in IDEA but there is no run configuration and no file is executable.

Thanks.

**Comment by SmiddyPence** [comment]
Hi 

In IntelliJ you should be able to right click any method annotated with @Koan and they choose RunAs Test. Once you have done that once it will also appear in the Run dropdown at the top.

The @Koan is basically the same as @Test if you are familiar with JUnit 

Let me know if that doesn't work out for you.

**Comment by profesorasix** [comment]
Hi,

The problem seems to be that maven expects test to be in src/test/java not in src/koan/java.
Need to set test directory in pom.xml

I've created a PR that seems to work.
Thanks.

**Comment by SmiddyPence** [comment]
Oh I see.  Yes that makes sense, I usually add it as a test source directory in the IDE.

This is a better way.

Thanks for PR, all help appreciated.
